sudo: required
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
install: true
jobs:
  include:
  - stage: Compilation and Installation
    script: scripts/travis.sh install
  - stage: Deploy on
    script: if [ "$TRAVIS_PULL_REQUEST" != "true" ]; then bash scripts/travis.sh deploy;
      fi
env:
  global:
  - secure: XPGUumaRqIhXmXFRUuqq4FaHOE1xJ/+PPl8qUXzJB6PBEyqCn3Vt26lt/o5vrMtD29CXafo2UhB3Y+WVsQqMkHvYf3R/boau501BAqFkVWbhYQYtuSxWEHVgijrcZ7S/Ew3YowMCynydKKZEfpoE929RnQgIi2+8hrZuWUWHt+S+U+dwfmQJReKqEKlMzkPUP9F36OqlWueBes0+zz7jF8cb+Zn9Tzod29SY6ICngpW3UMA99cCbS+LfgqfxdY/m5wOfsnTHE/Yjb47SkSRVJ+UZ67wwWdkZb+/S9MKPubBw+hR+UH3eKqSEfJa87YEG/ElKxQbihEK6vBVC36keChZIuaaij6/SzUCtxlYW9M/FowtC8LkLlRXWW4mcWi9Mzz6dTaHJHbRdjEUO0FSopJ9+UZ5vs1+e8fsUNn2MRUtQzGhtTQkpixx7woLxqh/QToi8vIFMzsYAd6XOxkpS4TRZjNQ7dQVZlIGMPhkLmbb0NwCCpqnrTbtSt/OwIUWLk0D4kYUuZPPg9iUtqE/iRQVpL11ABmfH1FbrYSDLbZ/4/5grftMy4sbMZNPR2Dry98e+UTISCPRKt/cGLWlMBmnaQpDzt4+f5PQnVf0+R498kwh7ikFnNVl0zq87AavG8M2qWrhAzZhL538pBq7fWi6ZCLyMQypesDa4NpT+0wc=
  - secure: Tg31SadYaC8EWIx2cQVPXyLA7RPtE7q+tK4OFVndMX1cxe5wWanLvNg9MMkbC+1+kdUruPy6i9J9bNhWi+d/C4o7uQ1eK0V/F2Pl0hHCPOYv9ZObiAxzm5cCRpFEbK5hOisZjGaQpONLvAYbuNcPgVQpvM/drwjsuWqPisV6Wde6c4CK0b3FS+dPxbiTf9uUFzoapsPuLsLKvRqf1kgMW9xkN3+HK9FH4sWD6J7Zkaxp6uGj1MAwppqu+Y28TV56YLAZgI628zLgvlZfAQkdQNQNr4h9tw5u3rUwjEwHGYmgFjcsvQ9W4dheh04VZfI0HIXEzkXb//TCriTiH+3928U0ue4aqHAfTU4GH2RKejDp8eWDjnnNZDRSeOcFtIrFH8SBclqIGMIEOvQQ+M+gILZyY1lG7njoae6qhgakuc9Bvb2CDlNJLQEZxXA07cHaCGaA0ZGh+7VeUq5KNcNqA9GsDHFQAvrXFkX92GswG3GXuz/vjLUJZx33Bhno0FcdNU65phDHyd2dNRvx4wqGkBJ7piKT/W/ROvn1JpL7iOa7o5HiQYdw69KcDqHLo+CO5tIAbFGgyJpCwaPWQ/LlsBBoL8ggi9IgbMD4TNNhZG77FbNkQxbH40el+MDh+MhicrcfT/nAlKCtmm4ifgLfsDvCTf6WIIXKrHjewLKbEX4=
  - secure: TgliDodOe71eYU/W6nIsseBU2IwcdA0cA8grxV5BQlmz0cMoB+brAtnBAKbvPIfnt9rqkVzFbqq3nEwTzAnFldhY9LyNBgJ5bPM7sggwuCBmxKGGWgokHHMBnMVzxU4I2J81SdKv/55Qo59GFYTVoPxaH2Iu8Bkkhv5ptIXkvxnez1v8Q5L835UUehtY6uhXpvh3setIKdZXQDtMPaiwO7BbGYO4zUdoswuVm15RChYTiBGJCX+KLIBBJmHnzTH8tEic6jtPhxUo8FYQB0gPKJF6mJjGU9PWlN1VyzytdyY9ldt8lhSmYmreifD0fI0iSPIuAUYDqyFW3iwdEKTGJ5xKJCqqX4RG4HVyfUPQnf+MU0/Ddh/97YEtuTlmQxBoFoizWJzbi+0FROZTvwF65/f45zJBcuzcgzwgEhwQ2daC3FfvYZ3+yEODqqKXB9g4KT01/qlMjpMqgAmxflX0SDrKnT0Fw/jnzXoeYKqti7kJATZF/DmZe1gLhzQHJxn5mlAHxWZmSAxFMf7GwlC64sf2/4neUp6Us6AlPnydqWtuQq6nflumtondKN2jwwbZRY6pbFhknHkEmiwS1HEJk7vG8kNi/5gE0k+PYZVzk+MURxCIlVFicFNqUbHgk33bgNKDzlnWvWf02gI6Lcp7MYlR3m2jaPkKwyQfFpYn4Ps=
